[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
authors = ["zitai"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18.0"
rand = "0.6.5"
